/* Executed only by TestBrowserManagerFlow, against isolated offline fixtures. */
(async () => {
  const resumed = JSON.parse(sessionStorage.getItem('hire.test.resume') || 'null');
  const checks = resumed?.checks || [];
  const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
  const find = selector => document.querySelector(selector);
  const assert = (value, message) => { if (!value) throw new Error(message); checks.push(message); };
  const assertLabels = screen => {
    for (const field of document.querySelectorAll('#app-view input:not([type="hidden"]), #app-view textarea, #app-view select')) {
      assert(field.labels?.length || field.getAttribute('aria-label') || field.getAttribute('aria-labelledby'), `${screen}: ${field.name || field.id} has an accessible label`);
    }
  };
  const wait = async (predicate, label) => {
    for (let i = 0; i < 800; i++) { if (predicate()) return; await sleep(20); }
    throw new Error(`Timed out: ${label}`);
  };
  const fill = (selector, value) => {
    const el = find(selector);
    if (!el) throw new Error(`Missing input: ${selector}`);
    el.value = value;
    el.dispatchEvent(new Event('input', { bubbles: true }));
  };
  const summary = text => [...document.querySelectorAll('summary')].find(el => el.textContent.trim() === text);
  const submit = (selector, button) => {
    const form = find(selector);
    form.requestSubmit(button ? form.querySelector(button) : form.querySelector('button[type=submit]'));
  };
  window.confirm = () => true;
  try {
    if (resumed) {
      await wait(() => find('#intake-text'), 'worker loaded after reload');
      assert(find('#intake-text').value === 'This unfinished draft must survive updates.', 'Task draft survives a full browser reload');
      find('[data-tab="refine"]').click();
      await wait(() => find('#definition-editor'), 'definition editor after reload');
      assert(find('.direct-editor').open, 'Editor disclosure survives reload');
      assert(find('#definition-editor').value === 'An unfinished job description draft.', 'Direct editor draft survives tabs and full reload');
      assertLabels('Direct editor');
      find('[data-action="discard-editor"]').click();
      await wait(() => find('#definition-editor').value !== 'An unfinished job description draft.', 'saved definition reloaded');
      find('[data-tab="files"]').click();
      await wait(() => find('form[data-form="new-file"]'), 'file browser');
      fill('form[data-form="new-file"] input[name="path"]', 'work/notes.md');
      submit('form[data-form="new-file"]');
      await wait(() => find('#file-editor'), 'file created');
      fill('#file-editor', 'An unfinished file draft.');
      find('[data-tab="details"]').click();
      await wait(() => find('form[data-form="worker-model"]'), 'settings tab');
      find('[data-tab="files"]').click();
      await wait(() => find('#file-editor'), 'file reopened');
      assert(find('#file-editor').value === 'An unfinished file draft.', 'File draft survives changing tabs');
      find('[data-action="save-file"]').click();
      await wait(() => document.querySelector('#toast').textContent.includes('Saved work/notes.md'), 'file saved');
      const bootstrap = await fetch('/api/bootstrap').then(r => r.json());
      const overwritten = await fetch('/api/workers/test-writer/files', { method: 'PUT', headers: { 'X-Hire-Token': bootstrap.token, 'Content-Type': 'application/json' }, body: JSON.stringify({ path: 'work/notes.md', content: 'A newer saved version.' }) });
      assert(overwritten.ok, 'A separate writer changed the fixture file');
      fill('#file-editor', 'A draft based on the old version.');
      find('[data-action="save-file"]').click();
      await wait(() => document.querySelector('#toast').textContent.includes('changed since you opened'), 'stale write refused');
      assert(find('#file-editor').value === 'A draft based on the old version.', 'A save conflict preserves the draft');
      find('[data-action="discard-editor"]').click();
      await wait(() => find('#file-editor').value === 'A newer saved version.', 'current file loaded after discarding draft');
      find('[data-tab="capabilities"]').click();
      await wait(() => find('form[data-form="remember-fact"]'), 'worker capabilities');
      find('[data-disclosure="remember-fact"]').open = true;
      fill('#memory-name', 'report-audience');
      fill('#memory-content', 'The manager needs the source date. Supplied in this task review.');
      submit('form[data-form="remember-fact"]');
      await wait(() => [...document.querySelectorAll('[data-action="capability-file"]')].some(b => b.textContent === 'report-audience.md'), 'memory saved');
      fill('#memory-name', 'report-audience');
      fill('#memory-content', 'This duplicate must not replace the saved memory.');
      submit('form[data-form="remember-fact"]');
      await wait(() => document.querySelector('#toast').textContent.includes('already exists'), 'duplicate memory refused');
      assert(find('#memory-content').value.includes('must not replace'), 'A rejected memory write preserves the draft');
      assert(!find('form[data-form="remember-fact"] button').disabled, 'Failed capability actions can be corrected and retried');
      const memory = await fetch('/api/workers/test-writer/files?path=state/kv/report-audience.md').then(r => r.json());
      assert(memory.content.startsWith('The manager needs'), 'Adding memory cannot overwrite an existing fact');
      find('[data-disclosure="new-skill"]').open = true;
      fill('#skill-name', 'review-notes');
      fill('#skill-description', 'Use when reviewing a note against supplied records.');
      fill('#skill-method', 'Read the supplied record. State its date. Compare each reported number to it.');
      submit('form[data-form="create-skill"]');
      await wait(() => document.querySelector('#toast').textContent.includes('Skill added'), 'method saved as a skill');
      const skill = await fetch('/api/workers/test-writer/files?path=skills/review-notes/SKILL.md').then(r => r.json());
      assert(skill.content.includes('State its date.'), 'The saved skill contains the manager’s method');
      find('[data-disclosure="new-specialist"]').open = true;
      fill('#specialist-name', 'source-reviewer');
      fill('#specialist-purpose', 'Check claims against their source records. Identify missing dates and evidence.');
      submit('form[data-form="create-specialist"]');
      await wait(() => find('[data-action="assign-specialist"]'), 'specialist created');
      assert(find('#task-specialist').value === '', 'Creating a specialist keeps the parent as the default task recipient');
      find('[data-action="assign-specialist"]').click();
      assert(find('#task-specialist').value === 'source-reviewer', 'A specialist can be assigned through the normal task composer');
      assert(!find('input[name="specialistNetwork"]').checked, 'Specialist internet access is an explicit task choice');
      assert(find('input[name="plan"]').disabled, 'A specialist receives one focused task');
      assert(!find('.composer-options').hidden, 'An existing task check stays visible when the recipient changes');
      fill('#intake-text', 'Check whether the note gives its source date. Explain missing evidence.');
      fill('input[name="check"]', 'grep -q body requests/*/RESULT.md');
      submit('form[data-form="intake"]');
      await wait(() => [...document.querySelectorAll('a.task-row')].some(a => a.textContent.includes('Perspective: source-reviewer')), 'perspective task listed');
      [...document.querySelectorAll('a.task-row')].find(a => a.textContent.includes('Perspective: source-reviewer')).click();
      await wait(() => summary('Exact command'), 'perspective task opened');
      assert(document.body.textContent.includes('agent specialist'), 'Specialist execution uses the public Agent command');
      assert((await fetch('/__test/work', { method: 'POST' })).ok, 'Specialist task completed');
      await wait(() => find('form[data-form="result-review"]'), 'specialist result ready for review');
      const perspectiveURL = location.pathname;
      const perspective = await fetch(`/api${perspectiveURL}`).then(r => r.json());
      assert(perspective.resultPath.startsWith('agents/source-reviewer/work/requests/'), 'The perspective result belongs to the specialist’s home');
      submit('form[data-form="result-review"]', 'button[value="accepted"]');
      await wait(() => document.body.textContent.includes('You accepted this result'), 'perspective accepted');
      find('a[href*="?perspective="]').click();
      await wait(() => find('#intake-text')?.value.includes('Evaluate its findings'), 'parent task drafted from the perspective');
      assert(find('#task-specialist').value === '', 'Using a perspective drafts a task for the parent');
      assert(find('#intake-text').value.includes(perspective.resultPath), 'The draft names the source findings to inspect');
      fill('#intake-text', `${find('#intake-text').value}Update the note to address the reviewer’s findings.`);
      submit('form[data-form="intake"]');
      await wait(() => [...document.querySelectorAll('a.task-row')].some(a => a.textContent.includes('Consider the perspective')), 'parent follow-up saved');
      const followup = [...document.querySelectorAll('a.task-row')].find(a => a.textContent.includes('Consider the perspective'));
      assert(!followup.textContent.includes('Perspective: source-reviewer'), 'The parent follow-up remains distinct from the specialist assignment');
    find('[data-action="retire"]').click();
    await wait(() => document.body.textContent.includes('are kept here for reference'), 'worker retired');
    assert(!find('form[data-form="intake"]'), 'Retired worker has no task composer');
    find('[data-tab="files"]').click();
    await wait(() => find('.file-layout'), 'archived files');
    assert(!find('form[data-form="new-file"]') && !find('[data-action="save-file"]'), 'Archived files have no write controls');
    find('[data-tab="details"]').click();
    await wait(() => document.querySelector('.settings-card'), 'archived settings');
    assert(!find('form[data-form="worker-model"]') && !find('[data-action="toggle-network"]'), 'Archived settings are read only');
    find('[data-tab="capabilities"]').click();
    await wait(() => document.body.textContent.includes('Learn from experience'), 'archived capabilities');
    assert(!find('form[data-form="remember-fact"]') && !find('form[data-form="create-skill"]'), 'Archived capabilities remain readable without write controls');
    document.querySelector('a.back').click();
    await wait(() => find('[data-disclosure="retired-workers"]'), 'archive on Team');
    find('[data-disclosure="retired-workers"]').open = true;
    assert(document.body.textContent.includes('Test Writer'), 'Retired worker stays accessible in the archive');
    document.querySelector('a[href="/hire"]').click();
    await wait(() => find('[data-disclosure="hire-examples"]'), 'supplied examples');
    find('[data-disclosure="hire-examples"]').open = true;
    find('a[href="/hire?example=reporting"]').click();
    await wait(() => find('form[data-form="example-hire"]'), 'example job description');
    assert(document.body.textContent.includes('Recomputes net sales'), 'The example explains exactly what its check establishes');
    find('[data-disclosure="example-task"]').open = true;
    assert(document.body.textContent.includes('inputs/sales.csv'), 'Inputs can be inspected before hiring the example');
    fill('#example-name', 'Sample Sales');
    submit('form[data-form="example-hire"]');
    await wait(() => find('[data-action="sample-task"]'), 'example hired with a first task available');
    assert(!find('a.task-row'), 'Hiring an example does not silently start its task');
    find('[data-action="sample-task"]').click();
    assert(find('#intake-text').value.includes('2026-09-01'), 'Supplied first task is loaded for review');
    assert(find('input[name="check"]').value === 'sh ../tools/example-check', 'Supplied task includes its real executable check');
    assert(!find('input[name="plan"]').checked, 'The sample stays one task without extra planning');
    submit('form[data-form="intake"]');
    await wait(() => find('a.task-row'), 'sample task saved');
    find('a.task-row').click();
    await wait(() => summary('What the automatic checks cover'), 'sample task opened');
    assert(document.body.textContent.includes('Amounts are signed integer cents'), 'Saved sample retains its specific instructions');
    } else {
    await wait(() => find('form[data-form="quick-hire"]'), 'Team loaded');
    document.querySelector('a[href="/hire"]').click();
    await wait(() => find('form[data-form="create-worker"]'), 'Hire loaded');
    assertLabels('Hire');
    assert(!find('input[name="reviewTeam"]').checked, 'Independent drafting reviews are an explicit choice');
    fill('form[data-form="builder-chat"] textarea', 'Create Test Writer to write short useful notes from supplied records.');
    submit('form[data-form="builder-chat"]');
    await wait(() => find('[data-action="builder-apply"]'), 'job description drafted');
    assert(!document.body.textContent.includes('Reviewed by'), 'An ordinary draft does not claim independent review');
    assert(find('[data-disclosure="draft-effort"] tbody td:nth-child(3)').textContent === '1', 'The draft records its one author call');
    find('[data-action="builder-apply"]').click();
    await wait(() => find('form[data-form="intake"]'), 'worker created');
    assert(document.body.textContent.includes('Start with one small, real task.'), 'A first-task next step is shown');
    assert(!find('input[name="plan"]').checked, 'Sending a task does not silently request AI planning');
    fill('#intake-text', 'Write a short note about the supplied information.');
    submit('form[data-form="intake"]');
    await wait(() => find('a.task-row'), 'task queued');
    const taskURL = find('a.task-row').getAttribute('href');
    find('a.task-row').click();
    await wait(() => summary('Under the hood'), 'task loaded');
    summary('Under the hood').click();
    summary('Exact command').click();
    summary('Exact command').focus();
    window.scrollTo(0, 300);
    const scroll = window.scrollY;
    await sleep(6500);
    assert(summary('Under the hood').parentElement.open, 'Outer details stay open through task refresh');
    assert(summary('Exact command').parentElement.open, 'Nested details stay open through task refresh');
    assert(document.activeElement === summary('Exact command'), 'Keyboard focus survives task refresh');
    assert(Math.abs(window.scrollY - scroll) < 3, 'Reading position survives task refresh');
    const range = document.createRange();
    range.selectNodeContents(summary('Exact command').parentElement.querySelector('pre'));
    window.getSelection().removeAllRanges();
    window.getSelection().addRange(range);
    const selected = window.getSelection().toString();
    await sleep(4500);
    assert(selected && window.getSelection().toString() === selected, 'Selected evidence stays selectable and copyable during refresh');
    window.getSelection().removeAllRanges();
    document.querySelector('a.back').click();
    await wait(() => find('#intake-text'), 'worker reopened');
    fill('#intake-text', 'This unfinished draft must survive updates.');
    find('[data-action="toggle-options"]').click();
    fill('input[name="check"]', 'test -s example.txt');
    find('[data-tab="work"]').focus();
    await sleep(5500);
    assert(find('#intake-text').value === 'This unfinished draft must survive updates.', 'Task draft survives worker refresh after focus leaves it');
    assert(find('input[name="check"]').value === 'test -s example.txt', 'Task options survive worker refresh');
    document.querySelector('a.task-row').click();
    await wait(() => summary('Exact command'), 'task reopened');
    assert(summary('Exact command').parentElement.open, 'Reading state survives navigation away and back');
    const executed = await fetch('/__test/work', { method: 'POST' });
    assert(executed.ok, 'Offline worker completed through the real controller');
    await wait(() => find('form[data-form="result-review"]'), 'result ready for review');
    assert(document.body.textContent.includes('Ready for review'), 'Checks passing leaves a result for manager review');
    find('[data-disclosure="result-feedback"]').open = true;
    fill('#result-feedback', 'Give the source date and explain the discrepancy.');
    submit('form[data-form="result-review"]', 'button[value="changes-requested"]');
    await wait(() => find('[data-action="revise-result"]'), 'feedback saved');
    find('[data-action="revise-result"]').click();
    await wait(() => document.body.textContent.includes('Original result and your feedback'), 'linked revision opened');
    assert(window.location.pathname !== taskURL, 'Correction creates a separate linked task');
    const revisionURL = window.location.pathname;
    [...document.querySelectorAll('a')].find(a => a.textContent === 'Original result and your feedback').click();
    await wait(() => document.body.textContent.includes('Follow revision task'), 'original links to revision');
    assert(document.body.textContent.includes('Give the source date'), 'Original feedback is preserved');
    [...document.querySelectorAll('a')].find(a => a.textContent === 'Follow revision task').click();
    await wait(() => window.location.pathname === revisionURL && summary('Exact command'), 'revision reopened');
    assert((await fetch('/__test/work', { method: 'POST' })).ok, 'Revision completed through the real controller');
    await wait(() => find('form[data-form="result-review"]'), 'revision ready for review');
    submit('form[data-form="result-review"]', 'button[value="accepted"]');
    await wait(() => document.body.textContent.includes('You accepted this result'), 'result accepted');
    assert(document.body.textContent.includes('Your review'), 'Manager acceptance is visible separately from execution');
    document.querySelector('a.back').click();
    await wait(() => find('[data-action="retire"]'), 'worker reopened for retirement');
    find('[data-action="add-routine"]').click();
    await wait(() => find('form[data-form="routine"]'), 'recurring task editor');
    assertLabels('Recurring task');
    fill('#routine-text', 'Prepare the daily source review.');
    submit('form[data-form="routine"]');
    await wait(() => find('[data-action="routine"][data-do="disable"]'), 'recurring task saved');
    find('[data-action="routine"][data-do="disable"]').click();
    await wait(() => find('[data-action="routine"][data-do="enable"]'), 'recurring task paused');
    find('[data-action="routine"][data-do="enable"]').click();
    await wait(() => find('[data-action="routine"][data-do="disable"]'), 'recurring task resumed');
    find('[data-action="routine"][data-do="delete"]').click();
    await wait(() => !find('.routine-row'), 'recurring task removed');
    assert(true, 'A manager can add, pause, resume and remove recurring work');
    const tabs = [...document.querySelectorAll('[role="tab"]')];
    tabs[0].focus();
    tabs[0].dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
    await wait(() => document.querySelector('[role="tab"][aria-selected="true"]')?.dataset.tab === 'refine', 'keyboard tab navigation');
    assert(document.querySelector('[role="tabpanel"]').getAttribute('aria-labelledby') === 'tab-refine', 'Tab panel is labelled by its active tab');
    await wait(() => find('#definition-editor'), 'job description editor loaded');
    find('.direct-editor').open = true;
    fill('#definition-editor', 'An unfinished job description draft.');
    find('[data-tab="work"]').click();
    await wait(() => find('a.task-row'), 'Work tab restored');
    sessionStorage.setItem('hire.test.resume', JSON.stringify({ checks }));
    window.location.reload();
    return;
    }
    sessionStorage.removeItem('hire.test.resume');
    document.body.dataset.testResult = 'passed';
    await fetch('/__test/result', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ checks }) });
  } catch (error) {
    document.body.dataset.testResult = 'failed';
    const pre = document.createElement('pre');
    pre.textContent = error.stack;
    document.body.append(pre);
    await fetch('/__test/result', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ error: error.stack, checks }) });
  }
})();
