/* Real UI/controller; isolated offline skill author and command fixtures. */
(async () => {
  const checks = [], find = selector => document.querySelector(selector);
  const assert = (ok, message) => { if (!ok) throw new Error(message); checks.push(message); };
  const wait = async (predicate, label) => { for (let i = 0; i < 900; i++) { if (predicate()) return; await fetch('/__test/pulse'); await new Promise(resolve => setTimeout(resolve,20)); } throw new Error('Timed out: '+label); };
  const visit = async (path,predicate) => { history.pushState({},'',path); dispatchEvent(new PopStateEvent('popstate')); await wait(predicate,path); };
  const fill = (el,value) => { el.value=value; el.dispatchEvent(new Event('input',{bubbles:true})); };
  const fit = label => assert(document.documentElement.scrollWidth <= document.documentElement.clientWidth+1,label+' fits the viewport');
  const base = '/api/workers/skill-reader/skills/sales-review', page = base.slice(4);
  try {
    await wait(()=>find('main'),'application');
    const bootstrap=await fetch('/api/bootstrap').then(r=>r.json());
    const api=async(path,body,method='POST')=>{ const response=await fetch(path,{method,headers:{'Content-Type':'application/json','X-Hire-Token':bootstrap.token},body:JSON.stringify(body)}); const data=await response.json(); if(!response.ok) throw new Error(JSON.stringify(data)); return data; };
    const first=await api('/api/workers/skill-reader/requests',{text:'Review the refund report.'});
    const second=await api('/api/workers/skill-reader/requests',{text:'Review another report.'});
    for (const task of [first.request,second.request]) await api('/api/workers/skill-reader/files',{path:`work/requests/${task.id}/RESULT.md`,content:'# Sales review\nRefunds were added incorrectly.\n'},'PUT');
    await visit('/workers/skill-reader?tab=capabilities',()=>find(`a[href="${page}"]`));
    assert(find(`a[href="${page}"]`).textContent==='Improve skill','Training exposes a visible improvement action');
    find(`a[href="${page}"]`).click();
    await wait(()=>find('form[data-form=skill-improve] input[type=file]'),'improvement form');
    let form=find('form[data-form=skill-improve]');
    const before=await fetch(base).then(r=>r.json());
    assert(find('[data-current-file="assets/keep.bin"]'),'The whole skill includes binary resources');
    fill(form.elements.goal,'Subtract refunds and keep sales totals and report resources working.');
    form.querySelector(`[data-work-result][value="${first.request.id}"]`).click();
    const input=form.querySelector('input[type=file]'), transfer=new DataTransfer();
    transfer.items.add(new File(['Refunds reduce sales.'], 'refund-policy.md',{type:'text/markdown'}));
    input.files=transfer.files; input.dispatchEvent(new Event('change',{bubbles:true}));
    await wait(()=>form.querySelector('[data-selected]')?.textContent.includes('Ready · source retained'),'ready material');
    fit('Improvement form');
    await visit('/workers/skill-reader?tab=capabilities',()=>find(`a[href="${page}"]`));
    await visit(page,()=>find('form[data-form=skill-improve] [data-selected]')?.textContent.includes('refund-policy.md'));
    form=find('form[data-form=skill-improve]');
    assert(form.elements.goal.value.includes('Subtract refunds'),'Feedback and materials survive navigation');
    assert(form.querySelector(`[data-work-result][value="${first.request.id}"]`).checked && !form.querySelector(`[data-work-result][value="${second.request.id}"]`).checked,'Individual work-result selections survive navigation');
    form.requestSubmit(form.querySelector('[type=submit]'));
    await wait(()=>find('[data-skill-test]') && !find('[data-skill-test]').disabled,'prepared proposal');
    const revisionPage=location.pathname;
    assert(find('[data-skill-apply]').disabled,'A proposal cannot be installed before checks pass');
    assert((await fetch(base).then(r=>r.json())).bundle.sha256===before.bundle.sha256,'Drafting preserves the installed skill');
    find('[data-compare-file="scripts/total.py"]').click();
    await wait(()=>find('.skill-file-compare'),'file comparison');
    assert(find('.skill-file-compare').textContent.includes("r.get('type')=='refund'"),'Original and proposed script content is reviewable');
    assert(find('.skill-change-reason a'),'The changed file explains its reason with a source citation');
    fit('Script comparison');
    await visit(find('.skill-change-reason a').getAttribute('href'),()=>find('[data-skill-source] h2'));
    assert(find('[data-skill-source]').textContent.includes('Subtract refunds'),'The citation opens the retained manager feedback');
    await visit(revisionPage,()=>find('[data-skill-test]') && !find('[data-skill-test]').disabled);
    find('[data-compare-file="assets/report-logo.bin"]').click();
    await wait(()=>find('.skill-file-compare')?.textContent.includes('Binary asset'),'binary comparison');
    assert(find('.skill-file-compare').textContent.includes('absent in this version'),'Added assets are distinguished from an unreadable file');
    const download=find('.skill-file-compare a[href$="download=1"]');
    assert([...new Uint8Array(await fetch(download.href).then(r=>r.arrayBuffer()))].join(',')==='0,1,2,3','The asset download preserves exact binary bytes');
    find('[data-check-file="totals.py"]').click();
    await wait(()=>find('[data-edit-check]'),'test preview');
    assert(find('[data-skill-check-preview]').textContent.includes('assert float(p.stdout)==expected'),'The manager can inspect real behavior checks');
    find('[data-skill-test]').click();
    await wait(()=>find('[data-skill-apply]') && !find('[data-skill-apply]').disabled,'passing proposed version');
    const rows=[...document.querySelectorAll('.skill-test-results li')];
    assert(rows.some(row=>row.textContent.includes('Refunds reduce total')&&row.textContent.includes('Original')&&row.textContent.includes('failed')),'Checks reveal the original refund defect');
    assert(rows.some(row=>row.textContent.includes('Refunds reduce total')&&row.textContent.includes('Proposed')&&row.textContent.includes('passed')),'Checks demonstrate the proposed refund correction');
    fit('Check results');
    find('[data-compare-file="scripts/total.py"]').click();
    await wait(()=>find('[data-edit-file]'),'editable proposed file');
    find('[data-edit-file]').click();
    let editor=find('#skill-file-edit');
    fill(editor,editor.value+'\n# Manager reviewed refund handling.\n');
    await visit(page,()=>find('.skill-history'));
    await visit(revisionPage,()=>find('[data-edit-file]'));
    assert(find('[data-edit-file]').textContent==='Resume unsaved edit','Unfinished file edits remain discoverable after navigation');
    find('[data-edit-file]').click();
    editor=find('#skill-file-edit');
    assert(editor.value.includes('# Manager reviewed refund handling.'),'Unfinished file content survives navigation');
    find('[data-skill-test]').click();
    await wait(()=>find('[data-skill-action-error]').textContent.includes('Save or cancel'),'unsaved edit protected');
    assert(!find('[data-skill-test]').disabled,'A refused action leaves controls usable');
    editor.form.requestSubmit(editor.form.querySelector('[type=submit]'));
    await wait(()=>!find('#skill-file-edit') && find('[data-skill-apply]').disabled,'saved edit invalidates checks');
    assert(find('[data-skill-results]').textContent.includes('No checks have run'),'Changed bytes require fresh results');
    find('[data-skill-test]').click();
    await wait(()=>find('[data-skill-apply]') && !find('[data-skill-apply]').disabled,'edited proposal passes');
    find('[data-skill-apply]').click();
    await wait(()=>find('[data-skill-revert]') && !find('[data-skill-revert]').disabled,'installed update');
    const installed=await fetch(base).then(r=>r.json());
    assert(installed.bundle.sha256!==before.bundle.sha256 && installed.bundle.files.some(f=>f.path==='assets/report-logo.bin'),'Applying installs the reviewed complete bundle');
    await visit(page,()=>find('.skill-history'));
    assert(find('.skill-history').textContent.includes('Improvement applied'),'The installed version remains in review history');
    find('.skill-history').click();
    await wait(()=>find('[data-skill-revert]'),'return to rollback');
    find('[data-skill-revert]').click();
    await wait(()=>find('.skill-phase')?.textContent.includes('Previous version restored'),'restored version');
    assert((await fetch(base).then(r=>r.json())).bundle.sha256===before.bundle.sha256,'Restore recovers every original file, directory and permission');
    fit('Restored review');
    find('[data-compare-file="scripts/total.py"]').click();
    await wait(()=>find('.skill-file-compare'),'final comparison');
    window.scrollTo(0,0);
    await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
    document.body.dataset.browserResult='passed';
    await fetch('/__test/result',{method:'POST',body:JSON.stringify({error:'',checks})});
  } catch(error) {
    document.body.dataset.browserResult='failed';
    await fetch('/__test/result',{method:'POST',body:JSON.stringify({error:error.stack||String(error),checks})});
  }
})();
