/* Connected services, employee permissions, and the skills that teach their use. */
(() => {
  'use strict';
  const enc = encodeURIComponent, arr = value => Array.isArray(value) ? value : [];
  const names = {ready:'Connected', checking:'Checking the service', 'signing-in':'Sign-in in progress', disconnected:'Disconnected', error:'Needs attention'};
  const callNames = {prepared:'Prepared', review:'Needs your approval', running:'Operation started', succeeded:'Operation succeeded', failed:'Service reported a problem', stopped:'Stopped', pending:'Service needs follow-up', uncertain:'Outcome needs review', resolved:'Reviewed by manager'};
  window.HireConnections = class {
    constructor(options) { Object.assign(this,options); }
    url(slug='',id='') { return `${slug ? '/workers/'+enc(slug) : ''}/connections${id ? '/'+enc(id) : ''}`; }
    async render(slug='',id='') {
      const data = await this.api('/api/connections');
      const worker = slug ? await this.api('/api/workers/'+enc(slug)) : null;
      if (id==='new') return this.setup(worker,data);
      if (id) {
        const {connection} = await this.api('/api/connections/'+enc(id));
        const access = slug ? await this.api('/api/workers/'+enc(slug)+'/connections') : null;
        return this.detail(worker,connection,arr(access?.connections).find(item=>item.connection.id===id),data);
      }
      this.list(worker,data);
    }
    page(title,body,worker) {
      const {esc} = this;
      this.mount(title,`<section class="page apps-page"><a class="back" data-link href="${worker ? '/workers/'+enc(worker.slug)+'?tab=details' : '/settings'}">← ${worker ? esc(worker.name)+' · Tools & access' : 'Settings'}</a>${body}</section>`,worker?'team':'settings');
      return document.querySelector('.apps-page');
    }
    list(worker,data) {
      const {esc} = this, slug=worker?.slug||'';
      const root=this.page('Connected apps',`<header class="page-head"><div><p class="eyebrow">${worker ? esc(worker.name)+' · Apps for the job' : 'Apps for your team'}</p><h1>Connected apps</h1><p class="lede">Connect the services your team works in. Choose each employee’s access, then teach the workflows that make them effective.</p></div><a class="button primary" data-link href="${this.url(slug,'new')}">Connect an app</a></header>
        <ol class="app-steps" aria-label="App setup"><li><strong>1. Connect</strong><span>Sign in to your service.</span></li><li><strong>2. Give access</strong><span>Choose what an employee may do.</span></li><li><strong>3. Teach</strong><span>Build a skill for the real job.</span></li></ol>
        ${!data.available ? '<p class="notice warn">MCP and MCPbox are missing from the selected Bench suite. Install them to connect services.</p>' : ''}
        <div class="app-grid">${arr(data.connections).map(c=>`<article class="app-card"><span class="app-monogram" aria-hidden="true">${esc(c.name.slice(0,1).toUpperCase())}</span><div><h2>${esc(c.name)}</h2><p class="app-status ${c.state==='ready'?'positive':''}">${esc(names[c.state]||c.state)}</p><p>${c.transport==='http'?'Online service':'Runs on this computer'} · ${arr(c.catalogue?.capabilities).filter(cap=>cap.kind==='tools').length} tools</p>${c.error?`<p class="form-error">${esc(c.error)}</p>`:''}<a class="button" data-link href="${this.url(slug,c.id)}">${worker?'Choose access & teach':'Manage connection'}</a></div></article>`).join('') || '<section class="block"><h2>Give your team the tools for the job</h2><p>Start with a service such as your CRM, documents, calendar or project tracker. Use its MCP address or connection configuration.</p><a class="button primary" data-link href="'+this.url(slug,'new')+'">Connect your first app</a></section>'}</div>`,worker);
      if(worker) this.activity(root,worker);
    }
    setup(worker,data,existing=null) {
      const {esc}=this,slug=worker?.slug||'';
      const root=this.page(existing?'Update sign-in':'Connect an app',`<header class="page-head"><div><p class="eyebrow">Step 1 · Connect a service</p><h1>${existing?'Update sign-in':'Connect an app'}</h1><p class="lede">Use the connection details from your service. Connecting discovers what it offers; employee access is a separate choice.</p></div></header>
        ${!existing?`<section class="block"><h2>Have a connection configuration?</h2><p>Paste the MCP configuration supplied by your service. Choose the service to fill the form below.</p><label for="app-import">Connection JSON</label><textarea id="app-import" rows="3" autocomplete="off" spellcheck="false" placeholder='{"mcpServers":{"my-app":{"url":"https://…/mcp"}}}'></textarea><div class="actions"><button class="button" type="button" data-import>Read configuration</button><label data-import-picker hidden>Service <select id="app-import-choice"></select></label></div><p data-import-error class="form-error" role="status"></p></section>`:''}
        <form class="block app-connect-form" autocomplete="off"><div class="field"><label for="app-name">App name</label><input id="app-name" required maxlength="120" placeholder="Sales CRM" ${existing?'readonly':''} value="${esc(existing?.name||'')}"></div>
        ${!existing?`<div class="field"><label for="app-transport">How does it connect?</label><select id="app-transport"><option value="http">Online · service URL</option><option value="stdio">On this computer · local program</option></select></div><div class="field" data-transport="http"><label for="app-url">MCP service address</label><input id="app-url" type="url" placeholder="https://your-service.example/mcp"><small>Use the service’s MCP endpoint, without a password or token in the URL.</small></div><div data-transport="stdio" hidden><div class="field"><label for="app-command">Program</label><input id="app-command" placeholder="/path/to/server or npx"><small>A program installed on this computer.</small></div><div class="field"><label for="app-args">Program arguments · JSON array</label><textarea id="app-args" rows="2" spellcheck="false" placeholder='["--option", "value"]'>[]</textarea><small>Arguments are passed as written. Put credentials in environment values below.</small></div></div><div class="field"><label for="app-protocol">Service compatibility</label><select id="app-protocol"><option value="legacy" ${data.legacyAvailable?'selected':'disabled'}>Existing MCP services · 2025 and earlier</option><option value="modern" ${data.legacyAvailable?'':'selected'}>New MCP services · 2026 stateless protocol</option></select>${!data.legacyAvailable?'<small>The compatibility client is not installed in this suite. Install mcp-legacy for earlier services.</small>':''}</div>`:''}
        <div class="field"><label for="app-auth">Sign-in method</label><select id="app-auth"><option value="none">No sign-in required</option><option value="token">Access token</option><option value="oauth" ${data.oauthAvailable?'':'disabled'}>Sign in with the service · OAuth</option><option value="headers">Custom authentication headers</option></select></div>
        <div class="field" data-auth="token" hidden><label for="app-token">Access token</label><input id="app-token" type="password" autocomplete="new-password"><small>Stored on this computer. It is supplied to the service when needed.</small></div>
        <div class="field" data-auth="headers" hidden><label for="app-headers">Authentication headers · JSON object</label><textarea id="app-headers" rows="3" spellcheck="false" autocomplete="off" placeholder='{"Authorization":"Bearer …"}'></textarea></div>
        <div data-auth="oauth" hidden><div class="field"><label for="app-client">Client ID</label><input id="app-client" value="${esc(existing?.clientId||'')}" placeholder="From the service’s app registration"></div><div class="field"><label for="app-client-secret">Client secret · if required</label><input id="app-client-secret" type="password" autocomplete="new-password"></div><div class="field"><label for="app-scopes">Requested access scopes · if required</label><input id="app-scopes" value="${esc(existing?.scopes||'')}" placeholder="Space-separated scopes supplied by the service"></div><div class="field"><label for="app-flow">Sign-in flow</label><select id="app-flow"><option value="auto">Use the service’s supported sign-in</option><option value="code">Browser sign-in</option><option value="device">Device code</option><option value="client-credentials">Service account</option></select></div><label class="check"><input type="checkbox" id="app-private" ${existing?.allowPrivate?'checked':''}>This is a private or local OAuth service</label></div>
        <div class="field" data-transport="stdio" ${existing?.transport==='stdio'?'':'hidden'}><label for="app-env">Environment values · JSON object, if required</label><textarea id="app-env" rows="3" autocomplete="off" spellcheck="false" placeholder='{"API_KEY":"…"}'></textarea><small>Only these explicitly supplied service values are added to the local program.</small></div>
        ${existing?'<p class="notice">Enter the complete replacement credentials. Saved secrets are never filled into this form.</p>':''}<p data-app-error class="form-error" role="alert"></p><div class="actions"><button class="button primary" type="submit">${existing?'Save sign-in & check':'Connect & check service'}</button><a class="button" data-link href="${this.url(slug,existing?.id||'')}">Cancel</a></div></form>`,worker);
      const form=root.querySelector('.app-connect-form'),field=id=>root.querySelector('#app-'+id);
      const update=()=>{
        const transport=existing?.transport||field('transport').value;
        for(const el of root.querySelectorAll('[data-transport]')) el.hidden=el.dataset.transport!==transport;
        for(const el of root.querySelectorAll('[data-auth]')) el.hidden=el.dataset.auth!==field('auth').value;
        if(!existing){ field('url').required=transport==='http';field('command').required=transport==='stdio'; }
      };
      if(existing){field('auth').value=existing.auth;field('flow').value=existing.oauthFlow||'auto';}
      field('transport')?.addEventListener('change',update);field('auth').addEventListener('change',update);update();
      const object=(id)=>{const value=field(id).value.trim();if(!value)return {};const result=JSON.parse(value);if(!result||Array.isArray(result)||typeof result!=='object'||Object.values(result).some(v=>typeof v!=='string'))throw new Error('Use a JSON object with text values for '+id+'.');return result;};
      let imported=[];
      const fillImport=()=>{
        const [name,c]=imported[Number(field('import-choice').value)];
        field('name').value=name;field('transport').value=c.url?'http':'stdio';field('url').value=c.url||'';field('command').value=c.command||'';field('args').value=JSON.stringify(c.args||[]);field('headers').value=JSON.stringify(c.headers||{});field('env').value=JSON.stringify(c.env||{});field('auth').value=c.headers&&Object.keys(c.headers).length?'headers':'none';update();
      };
      root.querySelector('[data-import]')?.addEventListener('click',()=>{
        try{ const value=JSON.parse(field('import').value);imported=Object.entries(value.mcpServers||value.servers||{});if(!imported.length)throw new Error('Use a configuration with at least one entry under mcpServers.');if(imported.some(([,c])=>!c||typeof c!=='object'||(!c.url&&!c.command)))throw new Error('Each service needs a URL or local program.');field('import-choice').innerHTML=imported.map(([name],i)=>`<option value="${i}">${esc(name)}</option>`).join('');root.querySelector('[data-import-picker]').hidden=imported.length<2;fillImport();root.querySelector('[data-import-error]').textContent='Configuration read. Check the fields below, then connect.';field('import').value='';}
        catch(error){root.querySelector('[data-import-error]').textContent=error.message;}
      });
      field('import-choice')?.addEventListener('change',fillImport);
      form.addEventListener('submit',async event=>{
        event.preventDefault();event.stopPropagation();const button=form.querySelector('[type=submit]');if(button.disabled)return;
        try{
          const auth=field('auth').value,transport=existing?.transport||field('transport').value;
          const body={auth,token:auth==='token'?field('token').value:'',headers:auth==='headers'?object('headers'):{},env:transport==='stdio'?object('env'):{},clientId:field('client').value,clientSecret:field('client-secret').value,scopes:field('scopes').value,oauthFlow:field('flow').value,allowPrivate:field('private').checked};
          if(!existing){Object.assign(body,{name:field('name').value,transport,url:transport==='http'?field('url').value:'',command:transport==='stdio'?field('command').value:'',args:transport==='stdio'?JSON.parse(field('args').value||'[]'):[],protocol:field('protocol').value});if(!Array.isArray(body.args)||body.args.some(v=>typeof v!=='string'))throw new Error('Program arguments must be a JSON array of text values.');}
          button.disabled=true;button.textContent='Connecting…';
          const result=await this.api('/api/connections'+(existing?'/'+enc(existing.id)+'/auth':''),{method:existing?'PUT':'POST',body});
          imported=[];form.reset();if(form.isConnected)this.navigate(this.url(slug,result.connection.id));
        }catch(error){if(form.isConnected)form.querySelector('[data-app-error]').textContent=error.message;}
        finally{button.disabled=false;button.textContent=existing?'Save sign-in & check':'Connect & check service';}
      });
    }
    status(c) {
      const {esc}=this,busy=['checking','signing-in'].includes(c.state),op=c.operation;
      const login=op?.loginUrl && /^https?:\/\//i.test(op.loginUrl) ? op.loginUrl : '';
      return `<p class="app-status ${c.state==='ready'?'positive':''}" role="status">${esc(names[c.state]||c.state)}</p>${busy?`<p>${c.state==='signing-in'?'Finish signing in with the service. Hire will check the connection after sign-in.':'Reading the service’s capabilities. No employee has received new access.'} You can leave this page and return.</p>`:''}${login?`<a class="button primary" href="${esc(login)}" target="_blank" rel="noopener noreferrer">Continue sign-in</a>${op.userCode?`<p>Enter this code: <strong>${esc(op.userCode)}</strong></p>`:''}`:''}${c.error?`<p class="notice warn">${esc(c.error)}</p>`:''}`;
    }
    detail(worker,c,access,data) {
      const {esc}=this,slug=worker?.slug||'',grant=access?.grant,mutable=!worker?.retiredAt&&!worker?.retiringAt,busy=['checking','signing-in'].includes(c.state);
      const root=this.page(c.name,`<header class="page-head"><div><p class="eyebrow">${worker?esc(worker.name)+' · Connected app':'Team connection'}</p><h1>${esc(c.name)}</h1><div data-app-status>${this.status(c)}</div></div><a class="button" data-link href="${this.url(slug)}">All connected apps</a></header>
        <section class="block"><h2>Connection</h2><p>${c.transport==='http'?esc(c.url):'Local program: '+esc(c.command)}</p><div class="actions">${c.enabled?`<button class="button" data-app-action="check" ${busy?'disabled':''}>Check connection</button><button class="button" data-app-auth ${busy?'disabled':''}>Update sign-in</button><button class="button danger-ghost" data-app-action="disconnect">Disconnect service</button>`:`<button class="button primary" data-app-action="reconnect">Reconnect service</button>`}</div><p class="muted">Disconnecting stops new calls for every employee using this service. Calls already sent may have taken effect.</p><p data-app-error class="form-error" role="alert"></p></section>
        ${worker ? `<section class="block" id="app-access"><p class="eyebrow">Step 2 · Give access</p><h2>What may ${esc(worker.name)} do?</h2><p>Choose the capabilities needed for the job. <strong>Use automatically</strong> permits the worker to call that tool without asking each time. <strong>Prepare for approval</strong> keeps each operation for your review in May.</p>${access?.accessChanged?'<p class="notice warn">The service changed some capabilities this employee uses. Review the updated descriptions and save access again.</p>':''}${grant&&!grant.enabled?'<p class="notice warn">This employee’s access has been revoked. Choose permissions below to restore access.</p>':''}
        ${c.enabled&&c.catalogue&&!busy?this.permissions(c,grant,mutable):'<p>Finish connecting and checking the service before assigning access.</p>'}</section><section class="block" id="app-teach"><p class="eyebrow">Step 3 · Teach the work</p><h2>Teach ${esc(worker.name)} to use ${esc(c.name)}</h2><p>A connection provides access. A skill teaches a method: which tool to choose, how to prepare inputs, check the result and handle exceptions.</p>${grant?.enabled&&c.enabled?`<form data-form="app-teach"><input type="hidden" name="workerSlug" value="${esc(slug)}"><div class="field"><label for="app-learning">What should the employee learn?</label><textarea id="app-learning" name="goal" rows="4" required maxlength="8192" placeholder="Find a customer by email, check for duplicates, then prepare a well-supported update using our CRM conventions."></textarea></div><p>The current permissions and service descriptions are included as cited sources. Add your guides, worked examples and corrections below.</p><p data-teach-error class="form-error" role="status"></p><button class="button primary" type="submit" ${mutable?'':'disabled'}>Prepare a service skill</button></form><div data-app-skills></div>`:'<p>Save this employee’s access first. Then prepare a skill from the permitted tools and your examples.</p>'}</section>`:`<section class="block"><h2>Give an employee access</h2><p>Each employee gets only the capabilities you choose. Connect an existing employee, then teach them how to use this service.</p><div data-app-team>Loading your team…</div></section><section class="block"><h2>What this service offers</h2>${this.catalogue(c)}</section>`}`,worker);
      for(const button of root.querySelectorAll('[data-app-action]'))button.addEventListener('click',async()=>{button.disabled=true;try{await this.api('/api/connections/'+enc(c.id)+'/'+button.dataset.appAction,{method:'POST',body:{}});if(root.isConnected)this.render(slug,c.id);}catch(error){root.querySelector('[data-app-error]').textContent=error.message;button.disabled=false;}});
      root.querySelector('[data-app-auth]')?.addEventListener('click',()=>this.setup(worker,data,c));
      if(worker){this.bindAccess(root,worker,c,grant);this.bindTeaching(root,worker,c);this.activity(root,worker,c.id);}
      else this.api('/api/workers').then(result=>{const team=root.querySelector('[data-app-team]');if(team?.isConnected)team.innerHTML=arr(result.workers||result).filter(w=>!w.retiredAt&&!w.retiringAt).map(w=>`<a class="button" data-link href="${this.url(w.slug,c.id)}">${esc(w.name)} · Choose access</a>`).join(' ')||'<a class="button primary" data-link href="/hire">Hire your first employee</a>';}).catch(error=>{if(root.isConnected)root.querySelector('[data-app-team]').textContent=error.message;});
      if(busy)this.watch(root,slug,c.id);
    }
    catalogue(c) { return arr(c.catalogue?.capabilities).map(cap=>this.capability(cap)).join('')||'<p>No capabilities are available yet.</p>'; }
    capability(cap,control='') {
      const {esc}=this,schema=cap.descriptor?.inputSchema||{},properties=Object.entries(schema.properties||{});
      return `<article class="app-capability"><div><h3>${esc(cap.title||cap.name.replaceAll('_',' '))}</h3><p>${esc(cap.description||'No description supplied by the service.')}</p><small>${esc(cap.kind==='tools'?'Tool':cap.kind==='resources'?'Reference':cap.kind==='templates'?'Reference lookup':'Service guidance')} · ${esc(cap.name)}</small>${properties.length?`<p class="app-inputs"><strong>Inputs:</strong> ${properties.map(([name,p])=>esc(name)+(arr(schema.required).includes(name)?' (required)':'')+(p.description?' — '+esc(p.description):'')).join('; ')}</p>`:''}</div>${control}</article>`;
    }
    permissions(c,grant,mutable) {
      const {esc}=this,caps=arr(c.catalogue.capabilities).filter(cap=>cap.kind!=='prompts');
      return `<form data-form="app-permissions" data-id="${esc(c.catalogue.sha256)}:${esc(grant?.version||'new')}"><div class="field"><label for="app-filter">Find a capability</label><input type="search" id="app-filter" placeholder="Search names and descriptions"></div><p><span data-permission-count>0</span> capabilities selected</p><div class="app-capabilities">${caps.map((cap,i)=>{const permission=arr(grant?.permissions).find(p=>p.kind===cap.kind&&p.name===cap.name&&p.digest===cap.digest);return this.capability(cap,`<label class="app-access-choice" for="app-permission-${i}">Employee access<select id="app-permission-${i}" name="permission-${i}" data-permission="${i}" ${mutable?'':'disabled'}><option value="">No access</option><option value="automatic" ${permission?.mode==='automatic'?'selected':''}>${cap.kind==='tools'?'Use automatically':'May read'}</option>${cap.kind==='tools'?`<option value="review" ${permission?.mode==='review'?'selected':''}>Prepare for approval</option>`:''}</select></label>`);}).join('')||'<p>This service offers no assignable tools or resources.</p>'}</div><div class="field"><label for="app-intent">How should this employee use the app?</label><textarea id="app-intent" name="instructions" rows="3" maxlength="8192" placeholder="Describe the intended work and any limits.">${esc(grant?.instructions||'')}</textarea></div><p data-access-error class="form-error" role="alert"></p><div class="app-save-bar"><button class="button primary" type="submit" ${mutable&&caps.length?'':'disabled'}>Save employee access</button>${grant?.enabled&&mutable?'<button class="button danger-ghost" type="button" data-revoke>Revoke employee access</button>':''}</div></form>`;
    }
    bindAccess(root,worker,c,grant) {
      const form=root.querySelector('[data-form="app-permissions"]');if(!form)return;
      const caps=arr(c.catalogue.capabilities).filter(cap=>cap.kind!=='prompts'),fields=[...form.querySelectorAll('[data-permission]')];
      const count=()=>form.querySelector('[data-permission-count]').textContent=fields.filter(f=>f.value).length;
      fields.forEach(f=>f.addEventListener('change',count));count();
      form.querySelector('#app-filter').addEventListener('input',event=>{const q=event.target.value.toLowerCase();for(const item of form.querySelectorAll('.app-capability'))item.hidden=!item.textContent.toLowerCase().includes(q);});
      form.addEventListener('submit',async event=>{event.preventDefault();event.stopPropagation();const button=form.querySelector('[type=submit]'),snapshot=this.reading.formSubmission(form);if(button.disabled)return;
        try{const permissions=fields.filter(f=>f.value).map(f=>{const cap=caps[Number(f.dataset.permission)];return{kind:cap.kind,name:cap.name,digest:cap.digest,mode:f.value};});if(!permissions.length)throw new Error('Choose at least one capability, or revoke this employee’s access.');button.disabled=true;await this.api('/api/workers/'+enc(worker.slug)+'/connections/'+enc(c.id),{method:'PUT',body:{catalogueSha256:c.catalogue.sha256,version:grant?.version||'',instructions:form.elements.instructions.value,permissions}});this.reading.forgetForm(form,snapshot);if(root.isConnected){await this.render(worker.slug,c.id);document.querySelector('#app-teach')?.scrollIntoView({block:'start'});}}
        catch(error){if(form.isConnected)form.querySelector('[data-access-error]').textContent=error.message;}finally{button.disabled=false;}
      });
      form.querySelector('[data-revoke]')?.addEventListener('click',async event=>{event.target.disabled=true;try{await this.api('/api/workers/'+enc(worker.slug)+'/connections/'+enc(c.id),{method:'DELETE'});if(root.isConnected)this.render(worker.slug,c.id);}catch(error){form.querySelector('[data-access-error]').textContent=error.message;event.target.disabled=false;}});
    }
    bindTeaching(root,worker,c) {
      const form=root.querySelector('[data-form="app-teach"]');if(!form)return;
      form.addEventListener('submit',async event=>{event.preventDefault();event.stopPropagation();const button=form.querySelector('[type=submit]');if(button.disabled)return;
        try{const ids=this.uploads.selected(form),snapshot=this.reading.formSubmission(form);button.disabled=true;await this.api('/api/workers/'+enc(worker.slug)+'/skills/drafts',{method:'POST',body:{goal:form.elements.goal.value,uploadIDs:ids,connectionId:c.id}});this.reading.forgetForm(form,snapshot);this.uploads.clear(form,ids);form.reset();this.teachingDrafts(root,worker,c);}
        catch(error){if(form.isConnected)form.querySelector('[data-teach-error]').textContent=error.message;}finally{button.disabled=false;}
      });
      this.teachingDrafts(root,worker,c);
    }
    async teachingDrafts(root,worker,c) {
      const target=root.querySelector('[data-app-skills]'),{esc,md}=this;if(!target?.isConnected)return;
      try{const result=await this.api('/api/workers/'+enc(worker.slug)+'/skills/drafts');if(!target.isConnected)return;
        const drafts=arr(result.drafts).filter(item=>item.draft.connectionId===c.id);
        const html=drafts.slice().reverse().map(({draft:d,sha256})=>`<article class="teaching-draft"><h3>${esc(d.name||d.goal)}</h3>${d.state==='installed'?`<p>Installed. Use a representative task to assess it, then improve the method, scripts and resources from results and feedback.</p><a class="button" data-link href="/workers/${enc(worker.slug)}/skills/${enc(d.installedPath.split('/')[1])}">Improve this skill</a>`:d.state==='ready'?`<p>Review the proposed method and its cited sources. Edit it before installing.</p><article class="prose">${md(d.method)}</article><form data-form="app-skill-install" data-id="${esc(d.id)}"><div class="field"><label for="${esc(d.id)}-name">Skill name</label><input id="${esc(d.id)}-name" name="name" value="${esc(d.name)}" required pattern="[a-z][a-z0-9-]*" maxlength="63"></div><div class="field"><label for="${esc(d.id)}-description">When to use it</label><input id="${esc(d.id)}-description" name="description" value="${esc(d.description)}" required maxlength="1024"></div><div class="field"><label for="${esc(d.id)}-method">Reviewed method</label><textarea id="${esc(d.id)}-method" name="method" rows="8" required maxlength="28000">${esc(d.method)}</textarea></div><p data-install-error class="form-error" role="status"></p><button class="button primary" type="submit">Install reviewed skill</button></form>`:`<p role="status">${esc(d.state==='drafting'?'Preparing a cited method. You can leave and return.':d.error||d.state)}</p>`}</article>`).join('');
        this.reading.replace(target,html);
        for(const form of target.querySelectorAll('[data-form="app-skill-install"]'))form.addEventListener('submit',async event=>{event.preventDefault();event.stopPropagation();const button=form.querySelector('[type=submit]');if(button.disabled)return;try{button.disabled=true;const {draft:d,sha256}=drafts.find(item=>item.draft.id===form.dataset.id);await this.api('/api/workers/'+enc(worker.slug)+'/skills',{method:'POST',body:{name:form.elements.name.value,description:form.elements.description.value,method:form.elements.method.value,uploadIDs:d.uploadIDs,draftID:d.id,draftSha256:sha256}});if(form.isConnected)this.teachingDrafts(root,worker,c);}catch(error){if(form.isConnected)form.querySelector('[data-install-error]').textContent=error.message;}finally{button.disabled=false;}});
        if(drafts.some(item=>item.draft.state==='drafting'))setTimeout(()=>this.teachingDrafts(root,worker,c),2000);
      }catch(error){if(target.isConnected)target.textContent=error.message;}
    }
    async watch(root,slug,id) {
      if(!root.isConnected)return;
      setTimeout(async()=>{if(!root.isConnected)return;try{const {connection:c}=await this.api('/api/connections/'+enc(id));if(!root.isConnected)return;if(['checking','signing-in'].includes(c.state)){root.querySelector('[data-app-status]').innerHTML=this.status(c);this.watch(root,slug,id);}else this.render(slug,id);}catch(error){if(root.isConnected)root.querySelector('[data-app-error]').textContent=error.message;}},1500);
    }
    async callDetail(worker,button) {
      const target=button.nextElementSibling,{esc,md}=this,id=button.dataset.callDetail;
      button.disabled=true;
      try{const {call,inputJSON,resultDataJSON}=await this.api('/api/workers/'+enc(worker.slug)+'/app-calls/'+enc(id));if(!target.isConnected)return;
        target.innerHTML=`${call.input?`<h4>Inputs</h4><pre class="app-json" tabindex="0">${esc(inputJSON)}</pre>`:''}${call.result?`<h4>Service result</h4>${arr(call.result.content).filter(item=>item.type==='text').map(item=>`<article class="prose">${md(item.text)}</article>`).join('')}<pre class="app-json" tabindex="0">${esc(resultDataJSON)}</pre>`:'<p>No terminal service result was recorded.</p>'}${call.resolution?`<p><strong>Your outcome review:</strong> ${esc(call.resolution==='confirmed-effect'?'Operation took effect':'Operation did not take effect')}</p><p>${esc(call.resolutionNote)}</p>`:''}
        ${['uncertain','pending','running'].includes(call.state)?`<form data-form="app-call-resolve" data-id="${esc(id)}"><h4>What did you verify in the service?</h4><p>Check the service itself before recording the outcome. This records your observation and allows new app work. It does not repeat or approve this operation.</p><div class="field"><label for="resolve-${esc(id)}">Observed outcome</label><select id="resolve-${esc(id)}" name="resolution"><option value="confirmed-effect">I confirmed the operation took effect</option><option value="confirmed-no-effect">I confirmed it did not take effect</option></select></div><div class="field"><label for="note-${esc(id)}">What you checked</label><textarea id="note-${esc(id)}" name="note" rows="3" required maxlength="8192"></textarea></div><p data-resolution-error class="form-error" role="status"></p><button class="button" type="submit">Record verified outcome</button></form>`:''}`;
        target.querySelector('form')?.addEventListener('submit',async event=>{event.preventDefault();event.stopPropagation();const form=event.target,submit=form.querySelector('[type=submit]');submit.disabled=true;try{await this.api('/api/workers/'+enc(worker.slug)+'/app-calls/'+enc(id)+'/resolve',{method:'POST',body:{resolution:form.elements.resolution.value,note:form.elements.note.value}});if(form.isConnected)this.render(worker.slug,call.connectionId);}catch(error){if(form.isConnected)form.querySelector('[data-resolution-error]').textContent=error.message;}finally{submit.disabled=false;}});
      }catch(error){if(target.isConnected)target.textContent=error.message;}finally{button.disabled=false;}
    }
    async activity(root,worker,id='') {
      const {esc,md}=this;
      try{const {calls}=await this.api('/api/workers/'+enc(worker.slug)+'/app-calls');if(!root.isConnected)return;
        const section=document.createElement('section');section.className='block app-activity';
        const visible=arr(calls).filter(call=>!id||call.connectionId===id).slice().reverse();
        section.innerHTML=`<h2>App activity</h2><p>Review the operations used for this employee’s tasks. An operation’s result is separate from completion of the whole task.</p>${visible.map(call=>`<article class="app-call"><h3>${esc(call.name.replaceAll('_',' '))}</h3><p class="app-status">${esc(callNames[call.state]||call.state)}</p><a data-link href="/workers/${enc(worker.slug)}/requests/${enc(call.requestId)}">Open the task</a>${call.error?`<p class="notice warn">${esc(call.error)}</p>`:''}${call.sourceError?`<p class="notice warn">${esc(call.sourceError)}</p>`:''}${call.state==='running'||call.state==='uncertain'||call.state==='pending'?'<p>Check the service before taking further action. Hire will not repeat this operation automatically.</p>':''}${call.reviewCommand?`<p>Review the exact operation in your terminal. May asks for your decision; no approval is given by this page.</p><pre class="app-command" tabindex="0">${esc(call.reviewCommand)}</pre>`:''}<button class="button" type="button" data-call-detail="${esc(call.id)}">Review inputs & result</button><div data-call-content="${esc(call.id)}"></div>${call.input?`<h4>Inputs</h4><pre class="app-json" tabindex="0">${esc(JSON.stringify(call.input,null,2))}</pre>`:''}${call.result?`<h4>Service result</h4>${arr(call.result.content).filter(item=>item.type==='text').map(item=>`<article class="prose">${md(item.text)}</article>`).join('')}${call.result.structuredContent?`<pre class="app-json" tabindex="0">${esc(JSON.stringify(call.result.structuredContent,null,2))}</pre>`:!call.result.content?`<pre class="app-json" tabindex="0">${esc(JSON.stringify(call.result,null,2))}</pre>`:''}`:''}${call.source?`<p><a href="${esc(call.source.url)}" target="_blank" rel="noopener">Read retained source and citation</a></p>`:''}</article>`).join('')||'<p>No app operations recorded yet. Give the employee a task that uses its connected service.</p>'}`;
        root.querySelector('.app-activity')?.remove();root.append(section);
        for(const button of section.querySelectorAll('[data-call-detail]'))button.addEventListener('click',()=>this.callDetail(worker,button));
      }catch(error){if(root.isConnected){const p=document.createElement('p');p.className='notice warn';p.textContent=error.message;root.append(p);}}
    }
  };
})();
